"""Add collaborative collections

Revision ID: b969536c333a
Revises: 147e96cea4ce
Create Date: 2026-03-09 15:00:22.354092

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b969536c333a'
down_revision = '147e96cea4ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('is_collaborative', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_name'), 'collection', ['name'], unique=False)
    op.create_table('collection_invitation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'receiver_id')
    )
    op.create_table('collection_member',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'user_id')
    )
    op.drop_table('watchlistitem')
    op.drop_table('watchedmedia')
    op.add_column('collection_item', sa.Column('collection_id', sa.Uuid(), nullable=True))
    op.add_column('collection_item', sa.Column('position', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.alter_column('collection_item', 'collection_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('collection_item_user_id_media_id_collection_name_key'), 'collection_item', type_='unique')
    op.create_unique_constraint('uq_user_media_collection', 'collection_item', ['user_id', 'media_id', 'collection_name', 'collection_id'])
    op.create_foreign_key('fk_collection_item_collection_id', 'collection_item', 'collection', ['collection_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_collection_item_collection_id', 'collection_item', type_='foreignkey')
    op.drop_constraint('uq_user_media_collection', 'collection_item', type_='unique')
    op.create_unique_constraint(op.f('collection_item_user_id_media_id_collection_name_key'), 'collection_item', ['user_id', 'media_id', 'collection_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('collection_item', 'collection_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('collection_item', 'position')
    op.drop_column('collection_item', 'collection_id')
    op.create_table('watchedmedia',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('media_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('watched_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('watchedmedia_media_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('watchedmedia_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('watchedmedia_pkey')),
    sa.UniqueConstraint('user_id', 'media_id', name=op.f('watchedmedia_user_id_media_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('watchlistitem',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('media_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('watchlistitem_media_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('watchlistitem_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('watchlistitem_pkey')),
    sa.UniqueConstraint('user_id', 'media_id', name=op.f('watchlistitem_user_id_media_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('collection_member')
    op.drop_table('collection_invitation')
    op.drop_index(op.f('ix_collection_name'), table_name='collection')
    op.drop_table('collection')
    # ### end Alembic commands ###
