/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSocialRouteImport } from './routes/_layout/social'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRecommendRouteImport } from './routes/_layout/recommend'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as LayoutDiscoverRouteImport } from './routes/_layout/discover'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutCollectionsIndexRouteImport } from './routes/_layout/collections/index'
import { Route as LayoutUsersUsernameRouteImport } from './routes/_layout/users/$username'
import { Route as LayoutCollectionsCollectionIdRouteImport } from './routes/_layout/collections/$collectionId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSocialRoute = LayoutSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecommendRoute = LayoutRecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDiscoverRoute = LayoutDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCollectionsIndexRoute = LayoutCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersUsernameRoute = LayoutUsersUsernameRouteImport.update({
  id: '/users/$username',
  path: '/users/$username',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCollectionsCollectionIdRoute =
  LayoutCollectionsCollectionIdRouteImport.update({
    id: '/collections/$collectionId',
    path: '/collections/$collectionId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/discover': typeof LayoutDiscoverRoute
  '/profile': typeof LayoutProfileRoute
  '/recommend': typeof LayoutRecommendRoute
  '/settings': typeof LayoutSettingsRoute
  '/social': typeof LayoutSocialRoute
  '/collections/$collectionId': typeof LayoutCollectionsCollectionIdRoute
  '/users/$username': typeof LayoutUsersUsernameRoute
  '/collections/': typeof LayoutCollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/discover': typeof LayoutDiscoverRoute
  '/profile': typeof LayoutProfileRoute
  '/recommend': typeof LayoutRecommendRoute
  '/settings': typeof LayoutSettingsRoute
  '/social': typeof LayoutSocialRoute
  '/': typeof LayoutIndexRoute
  '/collections/$collectionId': typeof LayoutCollectionsCollectionIdRoute
  '/users/$username': typeof LayoutUsersUsernameRoute
  '/collections': typeof LayoutCollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/discover': typeof LayoutDiscoverRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/recommend': typeof LayoutRecommendRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/social': typeof LayoutSocialRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/collections/$collectionId': typeof LayoutCollectionsCollectionIdRoute
  '/_layout/users/$username': typeof LayoutUsersUsernameRoute
  '/_layout/collections/': typeof LayoutCollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/discover'
    | '/profile'
    | '/recommend'
    | '/settings'
    | '/social'
    | '/collections/$collectionId'
    | '/users/$username'
    | '/collections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/discover'
    | '/profile'
    | '/recommend'
    | '/settings'
    | '/social'
    | '/'
    | '/collections/$collectionId'
    | '/users/$username'
    | '/collections'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/discover'
    | '/_layout/profile'
    | '/_layout/recommend'
    | '/_layout/settings'
    | '/_layout/social'
    | '/_layout/'
    | '/_layout/collections/$collectionId'
    | '/_layout/users/$username'
    | '/_layout/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/social': {
      id: '/_layout/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof LayoutSocialRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recommend': {
      id: '/_layout/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof LayoutRecommendRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/discover': {
      id: '/_layout/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof LayoutDiscoverRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/collections/': {
      id: '/_layout/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof LayoutCollectionsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users/$username': {
      id: '/_layout/users/$username'
      path: '/users/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof LayoutUsersUsernameRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/collections/$collectionId': {
      id: '/_layout/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof LayoutCollectionsCollectionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutDiscoverRoute: typeof LayoutDiscoverRoute
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutRecommendRoute: typeof LayoutRecommendRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSocialRoute: typeof LayoutSocialRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCollectionsCollectionIdRoute: typeof LayoutCollectionsCollectionIdRoute
  LayoutUsersUsernameRoute: typeof LayoutUsersUsernameRoute
  LayoutCollectionsIndexRoute: typeof LayoutCollectionsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutDiscoverRoute: LayoutDiscoverRoute,
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutRecommendRoute: LayoutRecommendRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSocialRoute: LayoutSocialRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCollectionsCollectionIdRoute: LayoutCollectionsCollectionIdRoute,
  LayoutUsersUsernameRoute: LayoutUsersUsernameRoute,
  LayoutCollectionsIndexRoute: LayoutCollectionsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
